sudo: false

language:
    - php
    - node_js

php:
    - 5.5

node_js:
    - 0.10

env:
    - WP_VERSION=trunk WP_MULTISITE=1

branches:
    only:
        - master

install:
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - cd dev-lib; git pull origin feature/pre-commit-improvements; cd -
    - source $DEV_LIB_PATH/travis.install.sh
    - dump_environment_variables

script:
    - source $DEV_LIB_PATH/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh
